apiVersion: v1
kind: Service
metadata:
  # Unique key of the Service instance
  name: service-springdatajpa

spec:
  selector:
    # Loadbalance traffic across Pods matching this label selector
    #KeyValuePair mylabel:springdatajpa mylabel is defined in first-pod.yaml
    mylabel: springdatajpa
    release: "1.0"

  ports:
    # Accept traffic sent to port 80 similar to -p arg in docker
    - name: http
      port: 8080
      #nodePort range Starts from 30,000
      nodePort: 30080
      targetPort: 80


    # Create an HA proxy in the cloud provider with an External IP address - *Only supported by some cloud providers*
    #type: LoadBalancer
  #type: ClusterIP
  #Expose a port through node.
  type: NodePort